method: deepsdf
data:
  train:
    dataset: SDFDataset
    meshes_dir: out/meshes/johnson/proc_v2/
    dataset_dir: out/datasets/johnson_deepsdf_v1/
    N_angles: 100
    splits:
      train: train.txt
training:
  out_dir: out/models/johnson_deepsdf_v2/
  learning_rate: 1.0e-3
  epochs: 10000
  epochs_per_save: 100
  epochs_per_validation: 100
  loss_weights:
    sdf_loss: 1.0
    embedding_loss: 100.0
    reg_loss: 0.0
model:
  z_object_size: 6