method: usdf
data:
  train:
    dataset: SDFDataset
    meshes_dir: out/meshes/johnson/proc_v2/
    dataset_dir: out/datasets/johnson_deepsdf_v5/
    N_angles: 32
    N_pc: 8661
    N_random: 25000
    N_off_surface: 250000
    N_sdf: 16384
    off_surface_sigma_a: 0.05
    off_surface_sigma_b: 0.015811388300841896
    splits:
      train: train.txt
training:
  out_dir: out/models/johnson_usdf_v5/
  learning_rate: 1.0e-3
  epochs: 11000
  epochs_per_save: 100
  epochs_per_validation: 100
  batch_size: 8
  loss_weights:
    sdf_loss: 1.0
    embedding_loss: 0.0
    reg_loss: 0.0
model:
  z_object_size: 16
  use_encoder: true