method: usdf
data:
  train:
    dataset: SDFDataset
    meshes_dir: out/meshes/johnson/proc_v2/
    dataset_dir: out/datasets/johnson_deepsdf_mem_v7/
    N_angles: 32
    N_random: 25000
    N_off_surface: 250000
    N_sdf: 120000
    N_pc: 9000
    off_surface_sigma_a: 0.05
    off_surface_sigma_b: 0.015811388300841896
    splits:
      train: train.txt
training:
  out_dir: out/models/density/model_gmm_v1/
  learning_rate: 1.0e-5
  epochs: 100000
  epochs_per_save: 100
  epochs_per_validation: 100
  batch_size: 4
  loss_weights:
    sdf_loss: 1.0
    embedding_loss: 0.0
    reg_loss: 1e-6
model:
  z_object_size: 8
  num_components: 3
  use_encoder: true
  distribution: gmm