method: usdf
data:
  train:
    dataset: UncertaintyDataset
    meshes_dir: out/meshes/shapenet/mugs_proc/
    dataset_dir: out/datasets/single_v1/
    splits:
      train: train_single_v1.txt
training:
  out_dir: out/models/single_v1/
  learning_rate: 1.0e-6
  epochs: 10000
  epochs_per_save: 100
  epochs_per_validation: 100
  loss_weights:
    sdf_loss: 1.0
    embedding_loss: 0.0
    reg_loss: 0.0
model:
  z_object_size: 16