method: deepsdf
data:
  train:
    dataset: SDFDataset
    meshes_dir: out/meshes/johnson/proc_v2/
    dataset_dir: out/datasets/johnson_deepsdf_v4/
    N_angles: 32
    N_pc: 8741
    N_random: 40000
    N_off_surface: 40000
    off_surface_sigma: 0.01
    splits:
      train: train.txt
training:
  out_dir: out/models/johnson_deepsdf_v4/
  learning_rate: 1.0e-3
  epochs: 10000
  epochs_per_save: 100
  epochs_per_validation: 100
  loss_weights:
    sdf_loss: 1.0
    embedding_loss: 100.0
    reg_loss: 0.0
model:
  z_object_size: 16